version: '3'
services:
  mongo:
    image: mongo
    container_name: mongo
    hostname: mongo
    ports:
      - "27017:27017"
    networks:
      - planet-express_planet-express-network
networks:
  planet-express-network:
    driver: bridge
